name: Guide Notebooks Regression
run-name: Guide Notebooks Regression
on: [push]
jobs:
  start-node-runner:
    runs-on: self-hosted, nobrainer-self-hosted-ci
    outputs:
      label: ${{ steps.srun.node_name }}
    steps:
      - name: sbatch
        run: |
          cat<<EOF > start_node_runner.sh
#!/bin/bash
#SBATCH -t 10
#SBATCH --mem=16G
#SBATCH -p gablab
set -ex
cd ${HOME}/actions-runner
./run.sh
EOF
          jobid=$(sbatch start_node_runner.sh | cut -d ' ' -f 4)
          while [ 1 ]; do
            node=$(squeue --noheader -j ${jobid} -o "%N")
            if [ -z ${node} ]; then
              sleep 1;
            else
              break;
            fi
          done

  guide-notebooks-regression:
    needs: start-node-runner
    runs-on: self-hosted, nobrainer-self-hosted-ci-runner
    steps:
      - run: echo "automatically triggered by a ${{ github.event_name }} event"
      - run: echo "running on a ${{ runner.os }} server hosted by github"
      - name: clone
        uses: actions/checkout@v3
      - name: install
        run: |
          cd ${{ github.workspace }}
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install jupyter
          pip install -e .
          nobrainer info
      - name: run
        run: |
          for notebook in $(ls guide/[0-9][0-9]-*.ipynb); do
            singularity exec \
              --nv -B /om \
              ${HOME}/img/tensorflow_latest-gpu.sif \
                ./run.sh \
                  jupyter nbconvert \
                    --execute ${notebook} \
                    --to markdown \
                    --stdout
          done
