name: Guide Notebooks Regression
run-name: Guide Notebooks Regression
on: [push]
jobs:
  guide_notebooks_regression:
    runs-on: [self-hosted, nobrainer-ci-ec2]
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: install
        run: |
          set -xe
          cd ${{ github.workspace }}
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install jupyter
          pip install -e .
          nobrainer info
      - name: run
        run: |
          set -xe
          cd ${{ github.workspace }}
          source env/bin/activate
          for notebook in $(ls guide/[0-9][0-9]-*.ipynb); do
            echo "running ${notebook}"
            jupyter nbconvert \
              --execute ${notebook} \
              --to markdown \
              --stdout
          done
