name: Guide Notebooks Regression
run-name: ${{ github.actor }}
on: [push]
jobs:
  guide-notebooks-regression:
    runs-on: ubuntu-latest
    steps:
      - run: echo "automatically triggered by a ${{ github.event_name }} event"
      - run: echo "running on a ${{ runner.os }} server hosted by github"
      - name: clone
        uses: actions/checkout@v3
      - name: install
        run: |
          cd ${{ github.workspace }}
          pip install --upgrade pip
          pip install -e .
          nobrainer info
      - name: run
        run: |
          for notebook in $(ls guide/[0-9][0-9]-*.ipynb); do
            jupyter nbconvert --execute ${notebook} --to html --stdout
          done
