name: Guide Notebooks Regression
run-name: Guide Notebooks Regression
on: [push]
jobs:
  start_node_runner:
    runs-on: [self-hosted, nobrainer-self-hosted-ci]
    outputs:
      jobid: ${{ steps.sbatch.outputs.jobid }}
    steps:
      - name: sbatch
        id: sbatch
        run: |
          jobid=$(sbatch \
                    -t 100 \
                    --mem 16G \
                    -p gablab \
                    -D ${HOME}/actions-runner \
                    run.sh | cut -d ' ' -f 4)
          echo "Submitted batch job with id ${jobid}"
          echo "Waiting for job to start"
          while [ 1 ]; do
            node=$(squeue --noheader -j ${jobid} -o "%N")
            echo "Found node ${node}"
            if [ -z ${node} ]; then
              sleep 1;
            else
              break;
            fi
          done
          echo "jobid=${jobid}" >> "$GITHUB_OUTPUT"

  guide_notebooks_regression:
    needs: start_node_runner
    runs-on: [self-hosted, nobrainer-ci-self-hosted-runner]
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: install
        run: |
          cd ${{ github.workspace }}
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install jupyter
          pip install -e .
          nobrainer info
      - name: run
        run: |
          cd ${{ github.workspace }}
          for notebook in $(ls guide/[0-9][0-9]-*.ipynb); do
            echo "running ${notebook} from ${PWD}"
            echo $(ls {$PWD})
            singularity exec \
              --nv \
              -B /om \
              ${HOME}/img/tensorflow_latest-gpu.sif \
                bash ${PWD}/run-in-env.sh \
                  jupyter nbconvert \
                    --execute ${PWD}/${notebook} \
                    --to markdown \
                    --stdout
          done

  shutdown_node_runner:
    if: always()
    needs: [start_node_runner, guide_notebooks_regression]
    runs-on: [self-hosted, nobrainer-self-hosted-ci]
    steps:
      - name: cleanup
        env:
          jobid: ${{ needs.start_node_runner.outputs.jobid }}
        run: |
          echo "jobid is ${jobid}"
          scancel ${jobid}
